name: Daily Currency Scraper

# Trigger
on:
  schedule:
    - cron: "0 5 * * *"   # Run every day at 8 AM Tanzania time
  workflow_dispatch:       # Allows manual run too

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install packages
      - run: pip install -r requirements.txt

      # Run your scraper
      - run: python scraper.py

      # Commit results back to repo
      - name: Save results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto update data" || echo "No changes"
          git push
